// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenketCorePracticeCore.Models.DataContext;

namespace VenketCorePracticeCore.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20190627105348_AddImagePathIntoEmployeeTable")]
    partial class AddImagePathIntoEmployeeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VenketCorePracticeCore.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Departments");

                    b.Property<string>("Emial");

                    b.Property<string>("Name");

                    b.Property<string>("imagePath");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Departments = 1,
                            Emial = "tayyab@gmail.com",
                            Name = "Tayyab"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
